version: "3.0"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - "./:/inss_discount"

  sidekiq:
    build: .
    depends_on:
      - inss_discount
      - db
      - redis
    volumes:
      - .:/rails
    command: sidekiq -C config/sidekiq.yml
    env_file:
      - .env

  inss_discount:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:create db:migrate
        bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    volumes:
      - .:/inss_discount
      - .:/rails
      - ./tmp:/rails/tmp
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

volumes:
  bundle_cache:
  postgres_data: {}
  app-storage: {}
