default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  host: <%= ENV["POSTGRES_HOST"] %>

development:
  <<: *default
  database: inss_discount_development

test:
  <<: *default
  database: inss_discount_test

production:
  <<: *default
  database: inss_discount_production
